name: CI and Pages Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install root deps
        run: npm install

      - name: Install server deps
        run: npm install
        working-directory: server

      - name: Install web deps
        run: npm install
        working-directory: web

      - name: Set dummy Supabase env for tests
        run: |
          echo "VITE_SUPABASE_URL=https://dummy.supabase.co" >> web/.env
          echo "VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.dummy" >> web/.env

      - name: Run Playwright tests (MCP gate)
        working-directory: web
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:4173
        run: |
          npx playwright install --with-deps
          npm run build
          npm run preview &
          npx wait-on http://localhost:4173
          npm test

      - name: Build web for Pages
        working-directory: web
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web/dist

  deploy:
    needs: test_and_build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
